training:
  batch_size: 64
  n_epochs: 500000
  n_iters: 10001
  snapshot_freq: 1000
  snapshot_sampling: false
  anneal_power: 2
  log_all_sigmas: false

sampling:
  batch_size: 512
  data_init: false
  step_lr: 0.0000062
  n_steps_each: 5
  ckpt_id: 50000
  final_only: true
  fid: true
  denoise: true
  num_samples4fid: 5000
  inpainting: false
  interpolation: false
  n_interpolations: 15

fast_fid:
  batch_size: 1024
  num_samples: 1000
  step_lr: 0.0000062
  n_steps_each: 5
<<<<<<< HEAD
  begin_ckpt: 50000
  ckpt_interval: 5000
  end_ckpt: 50000
=======
  begin_ckpt: 9000
  ckpt_interval: 1000
  end_ckpt: 9000
>>>>>>> 2ff1a8d74b5bf185f7cf5d44363a667da00d8dc7
  verbose: false
  ensemble: false

test:
  begin_ckpt: 5000
  end_ckpt: 10000
  batch_size: 100

data:
  dataset: "CIFAR10"
  image_size: 32
  channels: 3
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: true
  rescaled: false
  num_workers: 4

model:
  sigma_begin: 50
  num_classes: 232
  ema: true
  ema_rate: 0.999
  spec_norm: false
  sigma_dist: geometric
  sigma_end: 0.01
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 128

optim:
  weight_decay: 0.000
  optimizer: "DemonAdam"
  lr: 0.0001
  beta1: 0.9
  amsgrad: true
  eps: 0.00000001
