training:
  batch_size: 96
  n_epochs: 500000
  n_iters: 300001
  snapshot_freq: 1000
  snapshot_sampling: true
  anneal_power: 2
  log_all_sigmas: false
  channels_last: false
  amp: false

sampling:
  batch_size: 25
  data_init: false
  step_lr: 0.0000062
  n_steps_each: 10
  ckpt_id: 300000
  fid: false
  denoise: true
  num_samples4fid: 10000
  inpainting: false
  interpolation: false
  n_interpolations: 15

test:
  begin_ckpt: 5000
  end_ckpt: 10000
  batch_size: 100

data:
  dataset: "CIFAR10"
  image_size: 32
  channels: 3
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: true
  rescaled: false
  num_workers: 4

model:
  sigma_begin: 50
  num_classes: 232
  ema: true
  ema_rate: 0.999
  spec_norm: false
  sigma_dist: geometric
  sigma_end: 0.01
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 128
  variational: false

optim:
  weight_decay: 0.0
  optimizer: "AdaBelief"
  lr: 0.0001
  beta1: 0.9
  amsgrad: true
  eps: 0.00000001
