training:
  batch_size: 128
  n_epochs: 500000
  n_iters: 10001
  snapshot_freq: 1000
  snapshot_sampling: false
  anneal_power: 2
  log_all_sigmas: false

sampling:
  batch_size: 25
  data_init: false
  step_lr: 0.0000062
  n_steps_each: 100
  ckpt_id: 10000
  final_only: false
  fid: false
  denoise: true
  num_samples4fid: 10000
  inpainting: false
  interpolation: false
  n_interpolations: 15

fast_fid:
  batch_size: 128
  num_samples: 1000
  step_lr: 0.0000062
  n_steps_each: 5
  begin_ckpt: 1000
  ckpt_interval: 1000
  end_ckpt: 10000
  verbose: false
  ensemble: false

test:
  begin_ckpt: 5000
  end_ckpt: 10000
  batch_size: 100

data:
  dataset: "FashionMNIST"
  image_size: 28
  channels: 1
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: true
  rescaled: false
  num_workers: 4

model:
  sigma_begin: 1
  num_classes: 10
  ema: true
  ema_rate: 0.999
  spec_norm: false
  sigma_dist: geometric
  sigma_end: 0.01
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 64

optim:
  weight_decay: 0.000
  optimizer: "DemonAdam"
  lr: 0.001
  beta1: 0.9
  amsgrad: true
  eps: 0.00000001
